# https://github.com/KnpLabs/geekweek12/wiki/Routing

homepage:
    pattern: /
    defaults: { _controller: App:Default:homepage }

app_buildings_index:
    pattern: /buildings
    defaults: { _controller: App:Buildings:index }
