# https://github.com/KnpLabs/geekweek12/wiki/Routing

homepage:
    pattern: /
    defaults: { _controller: App:Default:homepage }
    requirements: { _method: 'GET' }

app_buildings_index:
    pattern: /buildings
    defaults: { _controller: App:Buildings:index }
    requirements: { _method: 'GET' }

app_buildings_show:
    pattern: /buildings/{id}
    defaults: { _controller: App:Buildings:show }
    requirements: { _method: 'GET' }

app_rooms_index:
    pattern: /rooms
    defaults: { _controller: App:Rooms:index }
    requirements: { _method: 'GET' }

app_rooms_show:
    pattern: /rooms/{id}
    defaults: { _controller: App:Rooms:show }
    requirements: { _method: 'GET' }

app_bookings_index:
    pattern: /bookings
    defaults: { _controller: App:RoomBookings:index }
    requirements: { _method: 'GET' }

app_bookings_show:
    pattern: /bookings/{id}
    defaults: { _controller: App:RoomBookings:show }
    requirements: { _method: 'GET' }