# https://github.com/KnpLabs/geekweek12/wiki/Routing

homepage:
    pattern: /
    defaults: { _controller: App:Default:homepage }

App:Buildings: ~
    # pattern: /buildings
    # defaults: { _controller: App:Building:all }
